### ISSUE TITLE
How to change email with my domain??

### ISSUE THREAD

**Issue by BuburAyams** [CapciGithub/Growtopia-CID-Creator-v3#2]
I've been following your project for a long time and it's really amazing

but here i have a problem ()
in previous versions I can change the email account that I will create.

as an example :
- growid : growid1
- email : growid1@menuju.my.id
- growid : growid2
- email : growid2@menuju.my.id

so I changed "@gmail.com" in the file : corefunc.h

but here I have a problem, there is no "corefunc.h" file and if i change @gmail.com which is in the "createidv3" file it will cause a run / deploy error

is there a solution?
thank you very much

**Comment by CapciGithub** [comment]
Hello, thanks for using my projects but sorry to say what you wanted is not really possible on v2 or neither v3. You can't change corefunc.h on this script you have to edit the config.json about your email etc. There's nothing different about v2 and v3 both of them same. On v2 and v3 versions you can't edit the @gmail.com but if you want to, i can add custom mail into this version so you can edit using config.json.

**Comment by BuburAyams** [comment]
Previously,
Thank you very much for the response,
yeah sorry, I mean v1 (Growtopia-CID-Creator),
in the "corefunc.h" file. I can edit "@gmail.com" to "@menuju.my.id", and it's true that in V2 & V3 I can't change it.

seems interesting, so this project (Growtopia-CID-Creator-v3) will be updated and add a custom mail domain?
And later can be in the settings / custom mail using config.json.

if that's true, I'm really looking forward update this project (Growtopia-CID-Creator-v3) by adding a custom mail option.
Maybe that's all, I owe you one

**Comment by CapciGithub** [comment]
> Previously, Thank you very much for the response, yeah sorry, I mean v1 (Growtopia-CID-Creator), in the "corefunc.h" file. I can edit "@gmail.com" to "@menuju.my.id", and it's true that in V2 & V3 I can't change it.
> 
> seems interesting, so this project (Growtopia-CID-Creator-v3) will be updated and add a custom mail domain? And later can be in the settings / custom mail using config.json.
> 
> if that's true, I'm really looking forward update this project (Growtopia-CID-Creator-v3) by adding a custom mail option. Maybe that's all, I owe you one

Yes, I will add option to customize your email from config.json and maybe, in future versions i might add customize start number for bot too. I will definitely check what you wanted tomorrow and release update for it.

**Comment by CapciGithub** [comment]
Custom email domain support added.

**Comment by BuburAyams** [comment]
I have to say it's pretty awesome,
Thank you very much for the fast response and fast action 
Have nice day,
God Bless You
